CASE_SUSPECTED = "suspected"
CASE_VERIFYING = "verifying"
CASE_CONFIRMED = "confirmed"
CASE_WAITING = "waiting"
CASE_ESCALATED = "escalated"
CASE_CLOSED = "closed"

TASK_CREATED = "created"
TASK_ASSIGNED = "assigned"
TASK_DONE = "done"
TASK_FAILED = "failed"

EXECUTOR_IDLE = "idle"
EXECUTOR_BUSY = "busy"
EXECUTOR_OFFLINE = "offline"
EXECUTOR_CHARGING = "charging"

EDGE_HYPOTHESIS = "hypothesis"
EDGE_CONFIRMED = "confirmed"
EDGE_REJECTED = "rejected"
EDGE_EXPIRED = "expired"

NODE_ZONE = "zone"
NODE_LANE = "lane"
NODE_SLOT = "slot"
NODE_CAMERA = "camera"
NODE_ROBOT = "robot"
NODE_EXECUTOR = "executor"
NODE_CASE = "case"
NODE_EVENT = "event"
NODE_TASK = "task"
NODE_EVIDENCE = "evidence"
NODE_DEVICE = "device"

REL_CONTAINS = "contains"
REL_NEAR = "near"
REL_OBSERVES = "observes"
REL_DETECTED = "detected"
REL_OCCURS_AT = "occurs_at"
REL_CREATES = "creates"
REL_SUPPORTS = "supports"
REL_REQUIRES = "requires"
REL_ASSIGNED_TO = "assigned_to"
REL_PRODUCES = "produces"
REL_VERIFIED = "verified"
REL_AFFECTS = "affects"
REL_OPERATES_IN = "operates_in"
REL_CONTROLS = "controls"

DEFAULT_CONFIDENCE = 60