CASE_SUSPECTED = "suspected"
CASE_VERIFYING = "verifying"
CASE_CONFIRMED = "confirmed"
CASE_WAITING = "waiting"
CASE_ESCALATED = "escalated"
CASE_CLOSED = "closed"

TASK_CREATED = "created"
TASK_ASSIGNED = "assigned"
TASK_DONE = "done"
TASK_FAILED = "failed"

EXECUTOR_IDLE = "idle"
EXECUTOR_BUSY = "busy"
EXECUTOR_OFFLINE = "offline"

NODE_ZONE = "zone"
NODE_LANE = "lane"
NODE_SLOT = "slot"
NODE_CAMERA = "camera"
NODE_ROBOT = "robot"
NODE_CASE = "case"
NODE_EVENT = "event"
NODE_TASK = "task"
NODE_EXECUTOR = "executor"
NODE_EVIDENCE = "evidence"