TASK_STATUS_CREATED = "created"
TASK_STATUS_ASSIGNED = "assigned"
TASK_STATUS_IN_PROGRESS = "in_progress"
TASK_STATUS_DONE = "done"
TASK_STATUS_FAILED = "failed"

EXECUTOR_STATUS_IDLE = "idle"
EXECUTOR_STATUS_BUSY = "busy"
EXECUTOR_STATUS_CHARGING = "charging"
EXECUTOR_STATUS_OFFLINE = "offline"

EVENT_STATUS_NEW = "new"
EVENT_STATUS_PROCESSED = "processed"
EVENT_STATUS_FAILED = "failed"

ROBOT_BATTERY_LOW_THRESHOLD = 15